name: openbrowser-espo-refusion
entrypoint: bash -c "python -m infra.eval.scripts.download_datasets --datasets formfactory && python -m infra.training.flow_matching.espo_refusion_trainer"
containerfile: infra/training/anyscale/Containerfile.online-grpo
compute_config:
  cloud: "Anyscale Cloud"
  head_node:
    instance_type: g6e.xlarge
  worker_nodes: []
working_dir: .
excludes:
  - .git
  - .env
  - __pycache__
  - node_modules
  - frontend
  - .cursor
  - presentation
  - data/mind2web/
  - data/webarena/
  - results/
  - outputs/
  - openbrowser_agent_data/
  - data/formfactory/.git/
  - data/formfactory/img/
  - "*.pyc"
env_vars:
  FLOW_TRAIN_FILE: "data/processed/formfactory_sft.jsonl"
  MAX_TRAIN_SAMPLES: "992"
  NUM_EPOCHS: "1"
  FLOW_LLM_SFT_CHECKPOINT: "/mnt/user_storage/openbrowser/checkpoints/flow-llm-sft/adapter"
  # ESPO hyperparameters (v19)
  GROUP_SIZE: "4"
  LR: "1e-5"
  KL_COEFF: "3e-3"
  EPSILON_LOW: "0.2"
  EPSILON_HIGH: "0.2"
  MU: "1"
  NUM_MC: "2"
  COUPLED: "true"
  GEN_STEPS: "64"
  GEN_TEMP: "1.0"
  SHUFFLE: "true"
  MIN_NONZERO: "1"
  EARLY_STOP_MAX_STEPS: "40"
  GRAD_CLIP: "1.0"
  # HF_TOKEN injected from .env at submission time by submit_job.py
max_retries: 1
timeout_s: 14400
tags:
  project: openbrowser
  task: espo-refusion
  model: refusion-8b-mdm
  method: espo-sequence-level
