name: openbrowser-eval-sft
entrypoint: python -m infra.training.finetuning.eval_sft
containerfile: infra/training/anyscale/Containerfile.online-grpo
compute_config:
  cloud: "Anyscale Cloud"
  head_node:
    instance_type: g5.xlarge
  worker_nodes: []
working_dir: .
excludes:
  - .git
  - .env
  - __pycache__
  - node_modules
  - frontend
  - .cursor
  - presentation
  - data/mind2web/
  - data/webarena/
  - results/
  - outputs/
  - openbrowser_agent_data/
  - data/formfactory/.git/
  - data/formfactory/img/
  - "*.pyc"
env_vars:
  TRAIN_FILE: "data/processed/formfactory_sft.jsonl"
  MAX_EVAL_SAMPLES: "25"
  SFT_CHECKPOINT_PATH: "/mnt/user_storage/openbrowser/checkpoints/sft"
  # HF_TOKEN injected from .env at submission time by submit_job.py
max_retries: 1
timeout_s: 7200
tags:
  project: openbrowser
  task: eval-sft
  model: qwen3-8b
