name: openbrowser-eval-fsdfm-sft
entrypoint: python -m infra.training.flow_matching.eval_fsdfm_sft
containerfile: infra/training/anyscale/Containerfile.online-fsdfm-grpo
compute_config:
  cloud: "Anyscale Cloud"
  head_node:
    instance_type: g5.xlarge
  worker_nodes: []
working_dir: .
excludes:
  - .git
  - .env
  - __pycache__
  - node_modules
  - frontend
  - .cursor
  - presentation
  - data/mind2web/
  - data/webarena/
  - results/
  - outputs/
  - openbrowser_agent_data/
  - data/formfactory/.git/
  - data/formfactory/img/
  - "*.pyc"
env_vars:
  FLOW_TRAIN_FILE: "data/processed/formfactory_sft.jsonl"
  MAX_EVAL_SAMPLES: "25"
  FSDFM_SFT_CHECKPOINT: "/mnt/user_storage/openbrowser/checkpoints/fsdfm-sft/lora_adapter"
  # HF_TOKEN injected from .env at submission time by submit_job.py
max_retries: 1
timeout_s: 7200
tags:
  project: openbrowser
  task: eval-fsdfm-sft
  model: fsdfm-1.3b-dfm
