name: openbrowser-finetuning-sft
entrypoint: python -m infra.training.finetuning.sft_trainer
image_uri: anyscale/ray:2.44.1-slim-py312-cu128
compute_config:
  cloud: "Anyscale Cloud"
  head_node:
    instance_type: g5.xlarge
  worker_nodes: []
working_dir: .
excludes:
  - .git
  - .env
  - __pycache__
  - node_modules
  - frontend
  - .cursor
  - presentation
  - data/mind2web/
  - data/webarena/
  - data/formfactory/
  - results/
  - outputs/
  - openbrowser_agent_data/
  - "*.pyc"
requirements:
  - torch>=2.0
  - transformers>=4.45
  - peft>=0.12
  - datasets>=2.18
  - accelerate>=0.28
  - bitsandbytes>=0.43
env_vars:
  TRAIN_FILE: "data/processed/formfactory_sft_train.jsonl"
  MAX_TRAIN_SAMPLES: "992"
  NUM_EPOCHS: "1"
  # HF_TOKEN injected from .env at submission time by submit_job.py
max_retries: 1
timeout_s: 14400
tags:
  project: openbrowser
  task: sft
  model: qwen3-8b
