name: openbrowser-flow-sft
entrypoint: python -m infra.training.flow_matching.flow_sft_trainer
image_uri: anyscale/ray:2.44.1-slim-py312-cu128
compute_config:
  cloud: "Anyscale Cloud"
  head_node:
    instance_type: g5.xlarge
  worker_nodes: []
working_dir: .
excludes:
  - .git
  - .env
  - __pycache__
  - node_modules
  - frontend
  - .cursor
  - presentation
  - data/mind2web/
  - data/webarena/
  - data/formfactory/
  - results/
  - outputs/
  - openbrowser_agent_data/
  - "*.pyc"
requirements:
  - torch>=2.0
  - transformers>=4.40
env_vars:
  FLOW_TRAIN_FILE: "data/processed/formfactory_flow.jsonl"
  MAX_TRAIN_SAMPLES: "200"
  NUM_EPOCHS: "5"
  # HF_TOKEN injected from .env at submission time by submit_job.py
max_retries: 1
timeout_s: 14400
tags:
  project: openbrowser
  task: flow-sft
  model: flow-byte-25m
