name: openbrowser-fsdfm-sft
entrypoint: python -m infra.training.flow_matching.fsdfm_sft_trainer
containerfile: infra/training/anyscale/Containerfile.online-fsdfm-grpo
compute_config:
  cloud: "Anyscale Cloud"
  head_node:
    instance_type: g5.xlarge
  worker_nodes: []
working_dir: .
excludes:
  - .git
  - .env
  - __pycache__
  - node_modules
  - frontend
  - .cursor
  - presentation
  - data/mind2web/
  - data/webarena/
  - results/
  - outputs/
  - openbrowser_agent_data/
  - data/formfactory/.git/
  - data/formfactory/img/
  - "*.pyc"
env_vars:
  FLOW_TRAIN_FILE: "data/processed/formfactory_sft_train.jsonl"
  MAX_TRAIN_SAMPLES: "500"
  NUM_EPOCHS: "5"
  # HF_TOKEN injected from .env at submission time by submit_job.py
max_retries: 1
timeout_s: 14400
tags:
  project: openbrowser
  task: fsdfm-sft
  model: fsdfm-1.3b-dfm
