name: openbrowser-online-flow-grpo
entrypoint: python -m infra.training.flow_matching.online_flow_grpo_trainer
containerfile: infra/training/anyscale/Containerfile.online-flow-grpo
compute_config:
  cloud: "Anyscale Cloud"
  head_node:
    instance_type: g5.xlarge
  worker_nodes: []
working_dir: .
excludes:
  - .git
  - .env
  - __pycache__
  - node_modules
  - frontend
  - .cursor
  - presentation
  - data/mind2web/
  - data/webarena/
  - results/
  - outputs/
  - openbrowser_agent_data/
  - "*.pyc"
env_vars:
  FLOW_TRAIN_FILE: "data/processed/formfactory_flow.jsonl"
  MAX_TRAIN_SAMPLES: "2"
  S3_CHECKPOINT_BUCKET: ""
  S3_CHECKPOINT_PREFIX: "training/checkpoints"
  AWS_REGION: "ca-central-1"
  # HF_TOKEN injected from .env at submission time by submit_job.py
max_retries: 1
timeout_s: 14400
tags:
  project: openbrowser
  task: online-flow-grpo
  model: flow-100m
